Homework2
made-ml-in-prod-2021/nickdndev pull request #3
Opened 2021-05-03 16:03 UTC by nickdndev

0) ветку назовите homework2, положите код в папку online_inference DONE 

1) Оберните inference вашей модели в rest сервис(вы можете использовать как FastAPI, так и flask, другие желательно не использовать, дабы не плодить излишнего разнообразия для проверяющих), должен быть endpoint /predict (3 балла)  DONE +3

Использовал FastApi

2) Напишите тест для /predict  (3 балла) (https://fastapi.tiangolo.com/tutorial/testing/, https://flask.palletsprojects.com/en/1.1.x/testing/) DONE +3

протестировал e2e для predict 

3) Напишите скрипт, который будет делать запросы к вашему сервису -- 2 балла DONE +2

make_request скрипт 

4) Сделайте валидацию входных данных (например, порядок колонок не совпадает с трейном, типы не те и пр, в рамках вашей фантазии)  (вы можете сохранить вместе с моделью доп информацию, о структуре входных данных, если это нужно) -- 3 доп балла
https://fastapi.tiangolo.com/tutorial/handling-errors/ -- возращайте 400, в случае, если валидация не пройдена  DONE +3

добавил проверку и @app.exception_handler(RequestValidationError) validation_exception_handler + pytest 

5) Напишите dockerfile, соберите на его основе образ и запустите локально контейнер(docker build, docker run), внутри контейнера должен запускать сервис, написанный в предущем пункте, закоммитьте его, напишите в readme корректную команду сборки (4 балл)  DONE +4

6) Оптимизируйте размер docker image (3 доп балла) (опишите в readme.md что вы предприняли для сокращения размера и каких результатов удалось добиться)  -- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/   DONE +3

Я сделал следующие шаги :
	1. сменил базовый контейнер с python:3.8 -> python:3.8-slim и получилось уменьшить размер с 1.3Gb до 611Mb 
	2. сделал отдельный файл для docker_requirements , чтобы не подтягивать pytest  и уменьшил с 611 Mb  -> 604Mb , но думаю есть получше способ, но не нашел его 
	
	также я думаю можно оптимизировать размер scikit-learn

7) опубликуйте образ в https://hub.docker.com/, используя docker push (вам потребуется зарегистрироваться) (2 балла)   DONE +2

https://hub.docker.com/repository/docker/nickml/online_inference

docker pull nickml/online_inference:v1

8) напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1 балл)
Убедитесь, что вы можете протыкать его скриптом из пункта 3  DONE +3

5) проведите самооценку -- 1 доп балл  DONE +1

Итого 24

2021-05-04 11:38 UTC, Mikhail-M commented
4) Что проверяет ваша валидация?

PS:
На доп баллы хотелось бы побольше проверок придумать, хотя бы порядок колонок, типы и тд и тп=)

2021-05-04 11:40 UTC, nickdndev commented
> 1. Что проверяет ваша валидация?
> 
> PS:
> На доп баллы хотелось бы побольше проверок придумать, хотя бы порядок колонок, типы и тд и тп=)
что в данных нет None

2021-05-04 12:24 UTC, nickdndev commented
> 1. Что проверяет ваша валидация?
> 
> PS:
> На доп баллы хотелось бы побольше проверок придумать, хотя бы порядок колонок, типы и тд и тп=)

добаил след.проверки :
- проверка на типы для данных + проверка на None
- проверка на features 
- проверка на shape data and features 
+ pytets


class DiagnosisRequest(BaseModel):
    data: List[conlist(Union[float, str], min_items=1, max_items=20)]
    features: List[str]

    @validator('features')
    def validate_model_features(cls, features):
        if not set(features).issuperset(FEATURES_MODELS):
            raise ValueError(f'Invalid features! Valid features are: {FEATURES_MODELS}')
        return features

    @validator('data')
    def validate_number_data_columns_and_features(cls, data):
        if np.array(data).shape[1] != len(FEATURES_MODELS):
            raise ValueError(f'Invalid columns number for data! Valid numbers are: {len(FEATURES_MODELS)}')
        return data

2021-05-04 14:29 UTC, sergey-msu commented on online_inference/src/app.py
> +    def validate_model_features(cls, features):
лучше писать self. Это не classmethod-ы

2021-05-04 14:30 UTC, sergey-msu commented on online_inference/src/app.py
> +class DiagnosisResponse(BaseModel):
ORM сущности можно выносить в отдельный модуль/ппекедж entities, как в прошлой домашке

2021-05-04 14:32 UTC, sergey-msu commented on online_inference/src/app.py
> +FEATURES_MODELS = {'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
Это можно было бы для лучшей конфигурабельности поместить в конфиг. Вообще можно его завести и конфигурировать API из него. Можно один файлик, без излишеств типа гидры.

2021-05-04 14:33 UTC, sergey-msu commented on online_inference/src/app.py
> +def load_object(path: str) -> dict:
вообще я бы распотрошил этот модуль для лучшей читаемости на какие-нибудь utils.py, entities.py и т.п. Не критично, но выглядело бы более структурированно

2021-05-04 14:39 UTC, sergey-msu commented on online_inference/src/app.py
> +model: Optional[dict] = None
Немного некомфортно с такими висящие глобальными объектами. В каком-нибудь falcon или flask можно было бы обернуть это в класс, инкапсулируюзий логику обработки запросов. Не знаю, можно ли это сделать в fastapi. Может если заморочиться, можно обернуть app = FastAPI()  и там инициализировать весь необходимый контекст.

Для такого маленького проекта, конечно, не критично. Просто мысли.

2021-05-04 14:41 UTC, sergey-msu commented on online_inference/src/app.py
> +        DiagnosisResponse(id=idx, diagnosis=int(diagnosis)) for idx, diagnosis in enumerate(predicts)
обычно idx объектов приходят как раз с запросом. А то мало ли, где может нарушится метчинг между объектами и предсказаниями. Опять же, для игрушечного проекта не критично

2021-05-04 14:43 UTC, nickdndev commented on online_inference/src/app.py
> +    def validate_model_features(cls, features):
https://pydantic-docs.helpmanual.io/usage/validators/
в доке они используют cls

2021-05-04 14:43 UTC, sergey-msu commented on online_inference/src/app.py
> +    model_path = os.getenv("PATH_TO_MODEL")
Тоже мысли: такие вещи как путь, хост и порт тоже можно было бы хранить в конфигах.

2021-05-04 14:46 UTC, nickdndev commented on online_inference/src/app.py
> +FEATURES_MODELS = {'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
согласен, но чтобы не перегружать код и сфокусироваться на docker и fastapi оставил коменты, что надо добавить конфиг ,если это пойдет в продакшен

2021-05-04 14:48 UTC, sergey-msu commented on online_inference/test/conftest.py
> +    os.environ['PATH_TO_MODEL'] = '../model/model.pkl'
тут надо подумать насчет scope временных переменных окружения, не перетирают ли они другие, должны ли быть восстановленны после тест сессии и т.п. Что-то об этом написано тут 
https://medium.com/@shay.palachy/temp-environment-variables-for-pytest-7253230bd777

если все ок, то ок

2021-05-04 14:49 UTC, sergey-msu commented on online_inference/src/app.py
> +def make_predict(data: List, features: List[str], model: dict, ) -> List[DiagnosisResponse]:
Желательно писать коменты хотя бы на все публичные методы и классы

2021-05-04 14:52 UTC, sergey-msu commented on online_inference/test/test_predict.py
> +def test_read_main(model_path):
тесты норм. Вроде все основное покрывают

2021-05-04 14:54 UTC, sergey-msu commented on online_inference/data/heart.csv
> +﻿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
в принципе полный датасет не особо нужен, если используется только для юниттестов.
Опять же, в данном случае он маленький, не принципиально

2021-05-04 14:56 UTC, sergey-msu reviewed
Кардинальных замечаний нет, есть мелкие недочеты. В остальном все по требованиям задания. Все замечания скорее по исправлению стиля, что актуально для более крупных проектов. С самооценкой согласен

2021-05-04 14:57 UTC, sergey-msu commented on online_inference/src/app.py
> +    def validate_model_features(cls, features):
да, я видел. Это их личный выбор :)

2021-05-04 14:58 UTC, sergey-msu commented on online_inference/src/app.py
> +FEATURES_MODELS = {'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope',
да, тут проект на один файлик, можно не множить сущности

2021-05-04 15:18 UTC, nickdndev commented on online_inference/src/app.py
> +class DiagnosisResponse(BaseModel):
согласен, но иногда не стоит всегда разбивать на модули т.к. если сервис легковесный или это MVP решение , то стоит делать как можно проще( т.к. надо думать еще про стоимость разработки)  и если будет наращиваться логика , то разбивать на модули .

Но все равно вынес в отдельный файл dto

2021-05-04 15:19 UTC, nickdndev commented on online_inference/src/app.py
> +def load_object(path: str) -> dict:
согласен, но иногда не стоит всегда разбивать на модули т.к. если сервис легковесный или это MVP решение , то стоит делать как можно проще( т.к. надо думать еще про стоимость разработки) и если будет наращиваться логика , то разбивать на модули .

2021-05-04 15:19 UTC, nickdndev commented on online_inference/src/app.py
> +model: Optional[dict] = None
спасибо, тоже об этом думал

2021-05-04 15:19 UTC, nickdndev commented on online_inference/src/app.py
> +        DiagnosisResponse(id=idx, diagnosis=int(diagnosis)) for idx, diagnosis in enumerate(predicts)
соглесен, внес изменения и поправил тесты

2021-05-04 15:20 UTC, nickdndev commented on online_inference/src/app.py
> +    model_path = os.getenv("PATH_TO_MODEL")
ага, потом можно вынести в конфиг

2021-05-04 15:20 UTC, nickdndev commented on online_inference/test/conftest.py
> +    os.environ['PATH_TO_MODEL'] = '../model/model.pkl'
ага, тесты нормально отработывают

2021-05-04 15:23 UTC, nickdndev commented on online_inference/src/app.py
> +def make_predict(data: List, features: List[str], model: dict, ) -> List[DiagnosisResponse]:
https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882

согласно философии клин кода , то если в коде есть комменты, то это плохой код . Название методов должно описывать основную идею.

Если рассматривать документация, то да она нужна , но опять надо думать про стоимость поддержки этой документации ,если идет активная разработка или это MVP проект

2021-05-04 15:23 UTC, nickdndev commented
> Кардинальных замечаний нет, есть мелкие недочеты. В остальном все по требованиям задания. Все замечания скорее по исправлению стиля, что актуально для более крупных проектов. С самооценкой согласен

Сережа, спасибо за ценные комментарии

2021-05-04 15:27 UTC, nickdndev commented on online_inference/data/heart.csv
> +﻿age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
да, он маленький и отлично подходит для тестов

2021-05-04 16:55 UTC, sergey-msu approved these changes
Уже этот писал коммент, но наверное не вошло в апрув.

В целом все ок. Проект маленький, поэтому все замечания носили необязательный характер и подоходят больше для более больших проектов. 
С самооценкой согласен.

2021-05-05 08:07 UTC, Mikhail-M requested changes
так в целом, всё хорошо, прошу поправить замечания и думаю с самооценкой буду согласен=)

Спасибо за скорость. 

@sergey-msu  отличное ревью

2021-05-05 08:07 UTC, Mikhail-M commented on online_inference/src/make_request.py
> +        print(request_data)
Что-то много всяких print

2021-05-05 08:07 UTC, Mikhail-M commented on online_inference/src/make_request.py
> +            "http://localhost:8000/predict/",
параметризовать мб?)

2021-05-05 08:07 UTC, Mikhail-M commented on online_inference/src/entites.py
> +    def validate_model_features(cls, features):
А может стоит еще порядок проверить?

2021-05-05 08:07 UTC, Mikhail-M commented on online_inference/src/make_request.py
> +        print(request_data)
В общем этот скрипт бы переписать, чтобы он стал отличаться от оригинального=)

2021-05-05 08:57 UTC, nickdndev commented on online_inference/src/make_request.py
> +        print(request_data)
добавил логирование + параметризация вызова  пример: --host "localhost" --port "8000" --dataset_path "data/heart.csv"

2021-05-05 08:58 UTC, nickdndev commented on online_inference/src/make_request.py
> +            "http://localhost:8000/predict/",
добавил параметризацию вызова пример: --host "localhost" --port "8000" --dataset_path "data/heart.csv"

2021-05-05 08:59 UTC, nickdndev commented on online_inference/src/entites.py
> +    def validate_model_features(cls, features):
добавил поверку на порядок колонок + pytest

2021-05-05 09:03 UTC, nickdndev commented
> так в целом, всё хорошо, прошу поправить замечания и думаю с самооценкой буду согласен=)
> 
> Спасибо за скорость.
> 
> @sergey-msu отличное ревью

Внес изменения, согласно комментам.

Михаил , возникло пару вопросов по докеру.

Мои шаги были для оптимизации:
1. сменил базовый контейнер с python:3.8 -> python:3.8-slim и получилось уменьшить размер с 1.3Gb до 611Mb
2. сделал отдельный файл для docker_requirements , чтобы не подтягивать pytest и уменьшил с 611 Mb -> 604Mb , но думаю есть получше способ, но не нашел его
3. уменьшил кол-во COPY и сделал это все в одной команде т.к. на каждый COPY создается отдельный слой (Only the instructions RUN, COPY, ADD create layers. Other instructions create temporary intermediate images, and do not increase the size of the build. : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

Есть лучше способ отделить зависимости от dev и docker env, я создавал два отдельных файла,чтобы не тянуть dev зависимости ?

В продакшине отимизириуют  размер scikit-learn для докер ?

2021-05-05 10:48 UTC, Mikhail-M approved these changes
Баллы: 24

2021-05-05 10:52 UTC, Mikhail-M commented
> > так в целом, всё хорошо, прошу поправить замечания и думаю с самооценкой буду согласен=)
> > Спасибо за скорость.
> > @sergey-msu отличное ревью
> 
> Внес изменения, согласно комментам.
> 
> Михаил , возникло пару вопросов по докеру.
> 
> Мои шаги были для оптимизации:
> 
> 1. сменил базовый контейнер с python:3.8 -> python:3.8-slim и получилось уменьшить размер с 1.3Gb до 611Mb
> 2. сделал отдельный файл для docker_requirements , чтобы не подтягивать pytest и уменьшил с 611 Mb -> 604Mb , но думаю есть получше способ, но не нашел его
> 3. уменьшил кол-во COPY и сделал это все в одной команде т.к. на каждый COPY создается отдельный слой (Only the instructions RUN, COPY, ADD create layers. Other instructions create temporary intermediate images, and do not increase the size of the build. : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
> 
> Есть лучше способ отделить зависимости от dev и docker env, я создавал два отдельных файла,чтобы не тянуть dev зависимости ?
> 
> В продакшине отимизириуют размер scikit-learn для докер ?


> > так в целом, всё хорошо, прошу поправить замечания и думаю с самооценкой буду согласен=)
> > Спасибо за скорость.
> > @sergey-msu отличное ревью
> 
> Внес изменения, согласно комментам.
> 
> Михаил , возникло пару вопросов по докеру.
> 
> Мои шаги были для оптимизации:
> 
> 1. сменил базовый контейнер с python:3.8 -> python:3.8-slim и получилось уменьшить размер с 1.3Gb до 611Mb
> 2. сделал отдельный файл для docker_requirements , чтобы не подтягивать pytest и уменьшил с 611 Mb -> 604Mb , но думаю есть получше способ, но не нашел его
> 3. уменьшил кол-во COPY и сделал это все в одной команде т.к. на каждый COPY создается отдельный слой (Only the instructions RUN, COPY, ADD create layers. Other instructions create temporary intermediate images, and do not increase the size of the build. : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
> 
> Есть лучше способ отделить зависимости от dev и docker env, я создавал два отдельных файла,чтобы не тянуть dev зависимости ?
> 
> В продакшине отимизириуют размер scikit-learn для докер ?

Как оптимизировать размер scikit-learn я не знаю

Что касается разных зависимостей для разных ситуаций, эту проблему можно было встретить еще в прошлой домашку, когда для исполнения пакета pytest и всякие faker не нужны, а для тестов нужны. 

Всякие файлики req-dev.txt более-менее стандартный подход
Еще в  tox https://tox.readthedocs.io/en/latest/example/devenv.html,  pipenv https://pipenv-fork.readthedocs.io/en/latest/advanced.html есть что-то для этого

2021-05-05 12:52 UTC, nickdndev commented
> > > так в целом, всё хорошо, прошу поправить замечания и думаю с самооценкой буду согласен=)
> > > Спасибо за скорость.
> > > @sergey-msu отличное ревью
> > 
> > 
> > Внес изменения, согласно комментам.
> > Михаил , возникло пару вопросов по докеру.
> > Мои шаги были для оптимизации:
> > 
> > 1. сменил базовый контейнер с python:3.8 -> python:3.8-slim и получилось уменьшить размер с 1.3Gb до 611Mb
> > 2. сделал отдельный файл для docker_requirements , чтобы не подтягивать pytest и уменьшил с 611 Mb -> 604Mb , но думаю есть получше способ, но не нашел его
> > 3. уменьшил кол-во COPY и сделал это все в одной команде т.к. на каждый COPY создается отдельный слой (Only the instructions RUN, COPY, ADD create layers. Other instructions create temporary intermediate images, and do not increase the size of the build. : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
> > 
> > Есть лучше способ отделить зависимости от dev и docker env, я создавал два отдельных файла,чтобы не тянуть dev зависимости ?
> > В продакшине отимизириуют размер scikit-learn для докер ?
> 
> > > так в целом, всё хорошо, прошу поправить замечания и думаю с самооценкой буду согласен=)
> > > Спасибо за скорость.
> > > @sergey-msu отличное ревью
> > 
> > 
> > Внес изменения, согласно комментам.
> > Михаил , возникло пару вопросов по докеру.
> > Мои шаги были для оптимизации:
> > 
> > 1. сменил базовый контейнер с python:3.8 -> python:3.8-slim и получилось уменьшить размер с 1.3Gb до 611Mb
> > 2. сделал отдельный файл для docker_requirements , чтобы не подтягивать pytest и уменьшил с 611 Mb -> 604Mb , но думаю есть получше способ, но не нашел его
> > 3. уменьшил кол-во COPY и сделал это все в одной команде т.к. на каждый COPY создается отдельный слой (Only the instructions RUN, COPY, ADD create layers. Other instructions create temporary intermediate images, and do not increase the size of the build. : https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
> > 
> > Есть лучше способ отделить зависимости от dev и docker env, я создавал два отдельных файла,чтобы не тянуть dev зависимости ?
> > В продакшине отимизириуют размер scikit-learn для докер ?
> 
> Как оптимизировать размер scikit-learn я не знаю
> 
> Что касается разных зависимостей для разных ситуаций, эту проблему можно было встретить еще в прошлой домашку, когда для исполнения пакета pytest и всякие faker не нужны, а для тестов нужны.
> 
> Всякие файлики req-dev.txt более-менее стандартный подход
> Еще в tox https://tox.readthedocs.io/en/latest/example/devenv.html, pipenv https://pipenv-fork.readthedocs.io/en/latest/advanced.html есть что-то для этого

@Mikhail-M Михаил , спасибо !

2021-05-05 12:52 UTC, merged

2021-05-05 15:17 UTC, Mikhail-M commented
@nickdndev еще extras_require в setup.py можно писать https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html

2021-06-01 07:27 UTC, Mikhail-M commented
проапдейтил баллы